export const clubPluginAbi = [{
  "inputs": [],
  "stateMutability": "nonpayable",
  "type": "constructor",
}, {
  "inputs": [{ "internalType": "address", "name": "target", "type": "address" }],
  "name": "AddressEmptyCode",
  "type": "error",
}, {
  "inputs": [{ "internalType": "address", "name": "account", "type": "address" }],
  "name": "AddressInsufficientBalance",
  "type": "error",
}, {
  "inputs": [{ "internalType": "address", "name": "implementation", "type": "address" }],
  "name": "ERC1967InvalidImplementation",
  "type": "error",
}, { "inputs": [], "name": "ERC1967NonPayable", "type": "error" }, {
  "inputs": [],
  "name": "FailedInnerCall",
  "type": "error",
}, { "inputs": [], "name": "InvalidInitialization", "type": "error" }, {
  "inputs": [],
  "name": "NotInitializing",
  "type": "error",
}, {
  "inputs": [{ "internalType": "address", "name": "token", "type": "address" }],
  "name": "SafeERC20FailedOperation",
  "type": "error",
}, { "inputs": [], "name": "UUPSUnauthorizedCallContext", "type": "error" }, {
  "inputs": [{
    "internalType": "bytes32",
    "name": "slot",
    "type": "bytes32",
  }], "name": "UUPSUnsupportedProxiableUUID", "type": "error",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "address", "name": "oldAuth", "type": "address" }, {
    "indexed": false,
    "internalType": "address",
    "name": "newAuth",
    "type": "address",
  }],
  "name": "AuthUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint16", "name": "oldPercent", "type": "uint16" }, {
    "indexed": false,
    "internalType": "uint16",
    "name": "newPercent",
    "type": "uint16",
  }],
  "name": "BidBucketPercentUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint16", "name": "oldRatio", "type": "uint16" }, {
    "indexed": false,
    "internalType": "uint16",
    "name": "newRatio",
    "type": "uint16",
  }],
  "name": "BidDepositRatioUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint16",
    "name": "oldCallPercent",
    "type": "uint16",
  }, { "indexed": false, "internalType": "uint16", "name": "newCallPercent", "type": "uint16" }],
  "name": "CallerPercentUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "address", "name": "oldNft", "type": "address" }, {
    "indexed": false,
    "internalType": "address",
    "name": "newNft",
    "type": "address",
  }],
  "name": "ClubMemberNFTUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint32",
    "name": "oldCooldown",
    "type": "uint32",
  }, { "indexed": false, "internalType": "uint32", "name": "cooldown", "type": "uint32" }],
  "name": "CooldownUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint256", "name": "oldCost", "type": "uint256" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "newCost",
    "type": "uint256",
  }],
  "name": "CostToCallUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint256", "name": "oldCost", "type": "uint256" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "newCost",
    "type": "uint256",
  }],
  "name": "CostToMintUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint256",
    "name": "oldGracePeriod",
    "type": "uint256",
  }, { "indexed": false, "internalType": "uint256", "name": "newGracePeriod", "type": "uint256" }],
  "name": "GracePeriodUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint64", "name": "version", "type": "uint64" }],
  "name": "Initialized",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint96", "name": "oldTrust", "type": "uint96" }, {
    "indexed": false,
    "internalType": "uint96",
    "name": "newTrust",
    "type": "uint96",
  }],
  "name": "MaxAuthTrustUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint256", "name": "oldPrice", "type": "uint256" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "newPrice",
    "type": "uint256",
  }],
  "name": "MemberBidPriceUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "address", "name": "member", "type": "address" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "trust",
    "type": "uint256",
  }],
  "name": "MemberTrustUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint16", "name": "oldRatio", "type": "uint16" }, {
    "indexed": false,
    "internalType": "uint16",
    "name": "newRatio",
    "type": "uint16",
  }],
  "name": "MintDepositRatioUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint16", "name": "oldPercent", "type": "uint16" }, {
    "indexed": false,
    "internalType": "uint16",
    "name": "newPercent",
    "type": "uint16",
  }],
  "name": "PercentageFullUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": false, "internalType": "uint256", "name": "oldPrice", "type": "uint256" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "",
    "type": "uint256",
  }],
  "name": "PublicBidPriceUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint256",
    "name": "roundRewards",
    "type": "uint256",
  }, { "indexed": false, "internalType": "address", "name": "winner", "type": "address" }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "amountToWinner",
    "type": "uint256",
  }, {
    "indexed": false,
    "internalType": "uint256",
    "name": "amountToBidBucket",
    "type": "uint256",
  }, { "indexed": false, "internalType": "uint256", "name": "checkpoint", "type": "uint256" }],
  "name": "RoundCompleted",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint256",
    "name": "oldPercent",
    "type": "uint256",
  }, { "indexed": false, "internalType": "uint256", "name": "newPercent", "type": "uint256" }],
  "name": "StartingPercentTrustUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{ "indexed": true, "internalType": "address", "name": "implementation", "type": "address" }],
  "name": "Upgraded",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint256",
    "name": "oldDuration",
    "type": "uint256",
  }, { "indexed": false, "internalType": "uint256", "name": "newDuration", "type": "uint256" }],
  "name": "VestingDurationUpdated",
  "type": "event",
}, {
  "anonymous": false,
  "inputs": [{
    "indexed": false,
    "internalType": "uint16",
    "name": "oldWinnerPercent",
    "type": "uint16",
  }, { "indexed": false, "internalType": "uint16", "name": "newWinnerPercent", "type": "uint16" }],
  "name": "WinnerPercentUpdated",
  "type": "event",
}, {
  "inputs": [],
  "name": "DENOMINATOR",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "MIN_MEMBER_NUM",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "NAME",
  "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "UPGRADE_INTERFACE_VERSION",
  "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "VERSION",
  "outputs": [{ "internalType": "string", "name": "", "type": "string" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "assetToken",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "auth",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "bidBucketBalance",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "bidBucketPercent",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "bidDepositRatio",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "callerPercent",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "checkpoint",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "recipient", "type": "address" }, {
    "internalType": "address",
    "name": "token",
    "type": "address",
  }], "name": "claim", "outputs": [], "stateMutability": "nonpayable", "type": "function",
}, {
  "inputs": [],
  "name": "clubMemberNFT",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "cooldown",
  "outputs": [{ "internalType": "uint32", "name": "", "type": "uint32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "costToCall",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "costToMint",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "tokenId", "type": "uint256" }],
  "name": "currentPercentTrust",
  "outputs": [{ "internalType": "uint256", "name": "percentTrust", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "feelingLucky",
  "outputs": [],
  "stateMutability": "payable",
  "type": "function",
}, {
  "inputs": [],
  "name": "fixedBid",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "gracePeriod",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "_safe", "type": "address" }, {
    "internalType": "address",
    "name": "_userManager",
    "type": "address",
  }, { "internalType": "address", "name": "_uToken", "type": "address" }, {
    "internalType": "address",
    "name": "_union",
    "type": "address",
  }, { "internalType": "address", "name": "_auth", "type": "address" }, {
    "internalType": "address",
    "name": "_assetToken",
    "type": "address",
  }, { "internalType": "uint96", "name": "_maxAuthTrust", "type": "uint96" }, {
    "internalType": "uint32",
    "name": "_cooldown",
    "type": "uint32",
  }], "name": "initialize", "outputs": [], "stateMutability": "nonpayable", "type": "function",
}, {
  "inputs": [],
  "name": "maxAuthTrust",
  "outputs": [{ "internalType": "uint96", "name": "", "type": "uint96" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "memberBidPrice",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "mintDepositRatio",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "bytes32[]", "name": "proof", "type": "bytes32[]" }],
  "name": "mintMemberNFT",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "tokenId", "type": "uint256" }],
  "name": "percentVested",
  "outputs": [{ "internalType": "uint256", "name": "percent", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "percentageFull",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "proRataAmount",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "proxiableUUID",
  "outputs": [{ "internalType": "bytes32", "name": "", "type": "bytes32" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "publicBidPrice",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "member", "type": "address" }],
  "name": "removeMember",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "safe",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "newAuth", "type": "address" }],
  "name": "setAuth",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "newPercent", "type": "uint16" }],
  "name": "setBidBucketPercent",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "newRatio", "type": "uint16" }],
  "name": "setBidDepositRatio",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "_callerPercent", "type": "uint16" }],
  "name": "setCallerPercent",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "nft", "type": "address" }],
  "name": "setClubMemberNFT",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint32", "name": "_cooldown", "type": "uint32" }],
  "name": "setCooldown",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "_costToCall", "type": "uint256" }],
  "name": "setCostToCall",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "newCost", "type": "uint256" }],
  "name": "setCostToMint",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "_gracePeriod", "type": "uint256" }],
  "name": "setGracePeriod",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint96", "name": "_maxAuthTrust", "type": "uint96" }],
  "name": "setMaxAuthTrust",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "newPrice", "type": "uint256" }],
  "name": "setMemberBidPrice",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "tokenId", "type": "uint256" }],
  "name": "setMemberTrust",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "newRatio", "type": "uint16" }],
  "name": "setMintDepositRatio",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "newPercent", "type": "uint16" }],
  "name": "setPercentageFull",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "newPrice", "type": "uint256" }],
  "name": "setPublicBidPrice",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "newPercent", "type": "uint256" }],
  "name": "setStartingPercentTrust",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "address[]",
    "name": "membersToUpdate",
    "type": "address[]",
  }, { "internalType": "uint96[]", "name": "amounts", "type": "uint96[]" }],
  "name": "setTrust",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint256", "name": "newDuration", "type": "uint256" }],
  "name": "setVestingDuration",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "uint16", "name": "_winnerPercent", "type": "uint16" }],
  "name": "setWinnerPercent",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [],
  "name": "startingPercentTrust",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "uToken",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "unionToken",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{
    "internalType": "address",
    "name": "newImplementation",
    "type": "address",
  }, { "internalType": "bytes", "name": "data", "type": "bytes" }],
  "name": "upgradeToAndCall",
  "outputs": [],
  "stateMutability": "payable",
  "type": "function",
}, {
  "inputs": [],
  "name": "userManager",
  "outputs": [{ "internalType": "address", "name": "", "type": "address" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "from", "type": "address" }, {
    "internalType": "address",
    "name": "to",
    "type": "address",
  }, { "internalType": "uint256", "name": "tokenId", "type": "uint256" }],
  "name": "validateUpdate",
  "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
  "stateMutability": "nonpayable",
  "type": "function",
}, {
  "inputs": [{ "internalType": "address", "name": "winner", "type": "address" }],
  "name": "validateWinner",
  "outputs": [{ "internalType": "bool", "name": "", "type": "bool" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "vestingDuration",
  "outputs": [{ "internalType": "uint256", "name": "", "type": "uint256" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "winnerPercent",
  "outputs": [{ "internalType": "uint16", "name": "", "type": "uint16" }],
  "stateMutability": "view",
  "type": "function",
}, {
  "inputs": [],
  "name": "withdrawRewards",
  "outputs": [],
  "stateMutability": "nonpayable",
  "type": "function",
}, { "stateMutability": "payable", "type": "receive" }];
